# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DownloadWindow(object):
    def setupUi(self, DownloadWindow):
        DownloadWindow.setObjectName("DownloadWindow")
        DownloadWindow.resize(800, 200)
        self.centralwidget = QtWidgets.QWidget(DownloadWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.downloadLabel = QtWidgets.QLabel(self.centralwidget)
        self.downloadLabel.setGeometry(QtCore.QRect(21, 18, 491, 16))
        self.downloadLabel.setObjectName("downloadLabel")
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 40, 751, 30))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.downloadVirtualSampleFilePath = QtWidgets.QLabel(self.layoutWidget_3)
        self.downloadVirtualSampleFilePath.setText("")
        self.downloadVirtualSampleFilePath.setObjectName("downloadVirtualSampleFilePath")
        self.horizontalLayout_7.addWidget(self.downloadVirtualSampleFilePath)
        self.browseDownloadVirtualSampleFileButton = QtWidgets.QPushButton(self.layoutWidget_3)
        self.browseDownloadVirtualSampleFileButton.setObjectName("browseDownloadVirtualSampleFileButton")
        self.horizontalLayout_7.addWidget(self.browseDownloadVirtualSampleFileButton)
        self.horizontalLayout_7.setStretch(0, 1)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(580, 130, 195, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.okDownloadButton = QtWidgets.QPushButton(self.layoutWidget)
        self.okDownloadButton.setObjectName("okDownloadButton")
        self.horizontalLayout_3.addWidget(self.okDownloadButton)
        self.cancelDownloadButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelDownloadButton.setObjectName("cancelDownloadButton")
        self.horizontalLayout_3.addWidget(self.cancelDownloadButton)
        DownloadWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DownloadWindow)
        self.statusbar.setObjectName("statusbar")
        DownloadWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DownloadWindow)
        QtCore.QMetaObject.connectSlotsByName(DownloadWindow)

    def retranslateUi(self, DownloadWindow):
        _translate = QtCore.QCoreApplication.translate
        DownloadWindow.setWindowTitle(_translate("DownloadWindow", "MainWindow"))
        self.downloadLabel.setText(_translate("DownloadWindow", "Please select the download path of the virtual sample file:"))
        self.browseDownloadVirtualSampleFileButton.setText(_translate("DownloadWindow", "Browse"))
        self.okDownloadButton.setText(_translate("DownloadWindow", "OK"))
        self.cancelDownloadButton.setText(_translate("DownloadWindow", "Cancel"))
