# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExportWindow(object):
    def setupUi(self, ExportWindow):
        ExportWindow.setObjectName("ExportWindow")
        ExportWindow.resize(800, 200)
        self.centralwidget = QtWidgets.QWidget(ExportWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(580, 130, 195, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.okExportButton = QtWidgets.QPushButton(self.layoutWidget)
        self.okExportButton.setObjectName("okExportButton")
        self.horizontalLayout_3.addWidget(self.okExportButton)
        self.cancelExportButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelExportButton.setObjectName("cancelExportButton")
        self.horizontalLayout_3.addWidget(self.cancelExportButton)
        self.exportLabel = QtWidgets.QLabel(self.centralwidget)
        self.exportLabel.setGeometry(QtCore.QRect(21, 18, 491, 16))
        self.exportLabel.setObjectName("exportLabel")
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 40, 751, 30))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.exportTrainingSamplePath = QtWidgets.QLabel(self.layoutWidget_3)
        self.exportTrainingSamplePath.setText("")
        self.exportTrainingSamplePath.setObjectName("exportTrainingSamplePath")
        self.horizontalLayout_7.addWidget(self.exportTrainingSamplePath)
        self.browseExportTrainingSampleFileButton = QtWidgets.QPushButton(self.layoutWidget_3)
        self.browseExportTrainingSampleFileButton.setObjectName("browseExportTrainingSampleFileButton")
        self.horizontalLayout_7.addWidget(self.browseExportTrainingSampleFileButton)
        self.horizontalLayout_7.setStretch(0, 1)
        ExportWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ExportWindow)
        self.statusbar.setObjectName("statusbar")
        ExportWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ExportWindow)
        QtCore.QMetaObject.connectSlotsByName(ExportWindow)

    def retranslateUi(self, ExportWindow):
        _translate = QtCore.QCoreApplication.translate
        ExportWindow.setWindowTitle(_translate("ExportWindow", "MainWindow"))
        self.okExportButton.setText(_translate("ExportWindow", "OK"))
        self.cancelExportButton.setText(_translate("ExportWindow", "Cancel"))
        self.exportLabel.setText(_translate("ExportWindow", "Please select the export path of the training sample:"))
        self.browseExportTrainingSampleFileButton.setText(_translate("ExportWindow", "Browse"))
