# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadWindow(object):
    def setupUi(self, LoadWindow):
        LoadWindow.setObjectName("LoadWindow")
        LoadWindow.resize(800, 243)
        self.centralwidget = QtWidgets.QWidget(LoadWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 40, 751, 30))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.trainingSampleFileName = QtWidgets.QLabel(self.layoutWidget_3)
        self.trainingSampleFileName.setText("")
        self.trainingSampleFileName.setObjectName("trainingSampleFileName")
        self.horizontalLayout_7.addWidget(self.trainingSampleFileName)
        self.browseTrainingSampleButton = QtWidgets.QPushButton(self.layoutWidget_3)
        self.browseTrainingSampleButton.setObjectName("browseTrainingSampleButton")
        self.horizontalLayout_7.addWidget(self.browseTrainingSampleButton)
        self.horizontalLayout_7.setStretch(0, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(21, 18, 192, 16))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(580, 180, 195, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.loadButton = QtWidgets.QPushButton(self.layoutWidget)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_3.addWidget(self.loadButton)
        self.cancelButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_3.addWidget(self.cancelButton)
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(19, 112, 751, 30))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.virtualSampleFileName = QtWidgets.QLabel(self.layoutWidget_4)
        self.virtualSampleFileName.setText("")
        self.virtualSampleFileName.setObjectName("virtualSampleFileName")
        self.horizontalLayout_8.addWidget(self.virtualSampleFileName)
        self.browseVirtualSampleButton = QtWidgets.QPushButton(self.layoutWidget_4)
        self.browseVirtualSampleButton.setObjectName("browseVirtualSampleButton")
        self.horizontalLayout_8.addWidget(self.browseVirtualSampleButton)
        self.horizontalLayout_8.setStretch(0, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 192, 16))
        self.label_2.setObjectName("label_2")
        LoadWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LoadWindow)
        self.statusbar.setObjectName("statusbar")
        LoadWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoadWindow)
        QtCore.QMetaObject.connectSlotsByName(LoadWindow)

    def retranslateUi(self, LoadWindow):
        _translate = QtCore.QCoreApplication.translate
        LoadWindow.setWindowTitle(_translate("LoadWindow", "MainWindow"))
        self.browseTrainingSampleButton.setText(_translate("LoadWindow", "Browse"))
        self.label.setText(_translate("LoadWindow", "Training Sample File:"))
        self.loadButton.setText(_translate("LoadWindow", "Load"))
        self.cancelButton.setText(_translate("LoadWindow", "Cancel"))
        self.browseVirtualSampleButton.setText(_translate("LoadWindow", "Browse"))
        self.label_2.setText(_translate("LoadWindow", "Virtual Sample File:"))
