# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveWindow(object):
    def setupUi(self, SaveWindow):
        SaveWindow.setObjectName("SaveWindow")
        SaveWindow.resize(800, 200)
        self.centralwidget = QtWidgets.QWidget(SaveWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.downloadLabel = QtWidgets.QLabel(self.centralwidget)
        self.downloadLabel.setGeometry(QtCore.QRect(21, 13, 491, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.downloadLabel.setFont(font)
        self.downloadLabel.setObjectName("downloadLabel")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(580, 130, 195, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.okDownloadButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.okDownloadButton.setFont(font)
        self.okDownloadButton.setObjectName("okDownloadButton")
        self.horizontalLayout_3.addWidget(self.okDownloadButton)
        self.cancelDownloadButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.cancelDownloadButton.setFont(font)
        self.cancelDownloadButton.setObjectName("cancelDownloadButton")
        self.horizontalLayout_3.addWidget(self.cancelDownloadButton)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 40, 751, 34))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.downloadContrastPicturePath = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.downloadContrastPicturePath.setFont(font)
        self.downloadContrastPicturePath.setText("")
        self.downloadContrastPicturePath.setObjectName("downloadContrastPicturePath")
        self.horizontalLayout_7.addWidget(self.downloadContrastPicturePath)
        self.browseDownloadContrastPictureButton = QtWidgets.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.browseDownloadContrastPictureButton.setFont(font)
        self.browseDownloadContrastPictureButton.setObjectName("browseDownloadContrastPictureButton")
        self.horizontalLayout_7.addWidget(self.browseDownloadContrastPictureButton)
        self.horizontalLayout_7.setStretch(0, 1)
        SaveWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SaveWindow)
        self.statusbar.setObjectName("statusbar")
        SaveWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SaveWindow)
        QtCore.QMetaObject.connectSlotsByName(SaveWindow)

    def retranslateUi(self, SaveWindow):
        _translate = QtCore.QCoreApplication.translate
        SaveWindow.setWindowTitle(_translate("SaveWindow", "MainWindow"))
        self.downloadLabel.setText(_translate("SaveWindow", "Please select the download path of the picture:"))
        self.okDownloadButton.setText(_translate("SaveWindow", "OK"))
        self.cancelDownloadButton.setText(_translate("SaveWindow", "Cancel"))
        self.browseDownloadContrastPictureButton.setText(_translate("SaveWindow", "Browse"))
