# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShowWindow(object):
    def setupUi(self, ShowWindow):
        ShowWindow.setObjectName("ShowWindow")
        ShowWindow.resize(1132, 516)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        ShowWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(ShowWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 20, 301, 161))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.showTrainingSampleScrollArea = QtWidgets.QScrollArea(self.widget)
        self.showTrainingSampleScrollArea.setGeometry(QtCore.QRect(0, 20, 301, 141))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.showTrainingSampleScrollArea.setFont(font)
        self.showTrainingSampleScrollArea.setWidgetResizable(True)
        self.showTrainingSampleScrollArea.setObjectName("showTrainingSampleScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 299, 139))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.showTrainingSampleScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.trainingSampleGraphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.trainingSampleGraphicsView.setGeometry(QtCore.QRect(320, 20, 801, 481))
        self.trainingSampleGraphicsView.setObjectName("trainingSampleGraphicsView")
        self.exportButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportButton.setGeometry(QtCore.QRect(10, 200, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.exportButton.setFont(font)
        self.exportButton.setObjectName("exportButton")
        ShowWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ShowWindow)
        QtCore.QMetaObject.connectSlotsByName(ShowWindow)

    def retranslateUi(self, ShowWindow):
        _translate = QtCore.QCoreApplication.translate
        ShowWindow.setWindowTitle(_translate("ShowWindow", "MainWindow"))
        self.label.setText(_translate("ShowWindow", "Selection:"))
        self.exportButton.setText(_translate("ShowWindow", "Export"))
